/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HouseHold);
  }
}(this, function(expect, HouseHold) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HouseHold.ProductLocationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductLocationApi', function() {
    describe('deleteProductLocationItem', function() {
      it('should call deleteProductLocationItem successfully', function(done) {
        //uncomment below and update the code to test deleteProductLocationItem
        //instance.deleteProductLocationItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductLocationCollection', function() {
      it('should call getProductLocationCollection successfully', function(done) {
        //uncomment below and update the code to test getProductLocationCollection
        //instance.getProductLocationCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductLocationItem', function() {
      it('should call getProductLocationItem successfully', function(done) {
        //uncomment below and update the code to test getProductLocationItem
        //instance.getProductLocationItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchProductLocationItem', function() {
      it('should call patchProductLocationItem successfully', function(done) {
        //uncomment below and update the code to test patchProductLocationItem
        //instance.patchProductLocationItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postProductLocationCollection', function() {
      it('should call postProductLocationCollection successfully', function(done) {
        //uncomment below and update the code to test postProductLocationCollection
        //instance.postProductLocationCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putProductLocationItem', function() {
      it('should call putProductLocationItem successfully', function(done) {
        //uncomment below and update the code to test putProductLocationItem
        //instance.putProductLocationItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
