/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HouseHold);
  }
}(this, function(expect, HouseHold) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HouseHold.ProductStockApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProductStockApi', function() {
    describe('deleteProductStockItem', function() {
      it('should call deleteProductStockItem successfully', function(done) {
        //uncomment below and update the code to test deleteProductStockItem
        //instance.deleteProductStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductStockCollection', function() {
      it('should call getProductStockCollection successfully', function(done) {
        //uncomment below and update the code to test getProductStockCollection
        //instance.getProductStockCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getProductStockItem', function() {
      it('should call getProductStockItem successfully', function(done) {
        //uncomment below and update the code to test getProductStockItem
        //instance.getProductStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchProductStockItem', function() {
      it('should call patchProductStockItem successfully', function(done) {
        //uncomment below and update the code to test patchProductStockItem
        //instance.patchProductStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postProductStockCollection', function() {
      it('should call postProductStockCollection successfully', function(done) {
        //uncomment below and update the code to test postProductStockCollection
        //instance.postProductStockCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putProductStockItem', function() {
      it('should call putProductStockItem successfully', function(done) {
        //uncomment below and update the code to test putProductStockItem
        //instance.putProductStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
