/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HouseHold);
  }
}(this, function(expect, HouseHold) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HouseHold.StockApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StockApi', function() {
    describe('deleteStockItem', function() {
      it('should call deleteStockItem successfully', function(done) {
        //uncomment below and update the code to test deleteStockItem
        //instance.deleteStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStockCollection', function() {
      it('should call getStockCollection successfully', function(done) {
        //uncomment below and update the code to test getStockCollection
        //instance.getStockCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getStockItem', function() {
      it('should call getStockItem successfully', function(done) {
        //uncomment below and update the code to test getStockItem
        //instance.getStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('patchStockItem', function() {
      it('should call patchStockItem successfully', function(done) {
        //uncomment below and update the code to test patchStockItem
        //instance.patchStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('postStockCollection', function() {
      it('should call postStockCollection successfully', function(done) {
        //uncomment below and update the code to test postStockCollection
        //instance.postStockCollection(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('putStockItem', function() {
      it('should call putStockItem successfully', function(done) {
        //uncomment below and update the code to test putStockItem
        //instance.putStockItem(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
