api_platform:
    title: 'HouseHold'
    description: 'HouseHold API'
    version: '0.0.9'
    show_webby: false

    collection:
        pagination:
            items_per_page: 50
    mapping:
        paths:
          - '%kernel.project_dir%/src/Stock/Domain'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    graphql:
        #default_ide: graphql-playground
        graphiql:
            enabled: true

    # The list of enabled formats. The first one will be the default.
    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    error_formats:
        jsonproblem:
            mime_types: ['application/problem+json']
        jsonld:
            mime_types: ['application/ld+json']

    path_segment_name_generator: App\Core\Infrastructure\Api\PathSegmentNameGeneratorSlash
