api_platform:
    title: 'HouseHold'
    description: 'HouseHold API'
    version: '1.0.0'
    show_webby: false

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    graphql:
        default_ide: graphql-playground
        graphiql:
            enabled: true
