framework:
    secret: '%env(APP_SECRET)%'
    default_locale: en

    cache:
        prefix_seed: "HH"
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: "redis://%env(REDIS_HOST)%:%env(REDIS_PORT)%/%env(REDIS_INDEX)%"

    session:
        handler_id: snc_redis.session.handler
        name: "HOUSEHOLD"

    #annotations:
    #    cache: cache.adapter.redis_native

    php_errors:
        log: true
    router:
        strict_requirements: ~
