version: '3.4'

services:
  php:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: php
    image: jorge07/cqrs:latest
  nginx:
    build:
      dockerfile: etc/artifact/Dockerfile
      context: .
      target: nginx
    image: jorge07/cqrs:nginx-latest
