apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-jwt
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  private.pem: {{ .Values.parameters.jwt.secretKey | b64enc | quote }}
  public.pem: {{ .Values.parameters.jwt.publicKey | b64enc | quote }}
  passphrase: {{ .Values.parameters.jwt.passphrase | b64enc | quote }}
