apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-mysql
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  host: {{ if .Values.mysql.selfHosted }} {{ template "mysqlHost" . }}{{ else }} {{ .Values.parameters.mysql.host | b64enc | quote }}{{ end }}
  user: {{ if .Values.mysql.selfHosted }} {{ .Values.mysql.mysqlUser | b64enc | quote }}{{ else }} {{ .Values.parameters.mysql.user | b64enc | quote }}{{ end }}
  pass: {{ if .Values.mysql.selfHosted }} {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}{{ else }} {{ .Values.parameters.mysql.pass | b64enc | quote }}{{ end }}
