apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-rabbitmq
  labels:
    app: {{ include "chart.name" . }}
    chart: {{ include "chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.rabbitmq.selfHosted }}
  host: {{ template "rabbitHost" . }}
  {{- else }}
  host: {{ .Values.parameters.rabbit.host | b64enc | quote }}
  {{- end }}
