doctrine:
    dbal:
        types:
          datetime_immutable: App\Core\Infrastructure\Share\Doctrine\DateTimeType
          datetime_micro: App\Core\Infrastructure\Share\Doctrine\DateTimeMicrosecondsType
