/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.HouseHold);
  }
}(this, function(expect, HouseHold) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new HouseHold.InlineResponse200HydraView();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse200HydraView', function() {
    it('should create an instance of InlineResponse200HydraView', function() {
      // uncomment below and update the code to test InlineResponse200HydraView
      //var instane = new HouseHold.InlineResponse200HydraView();
      //expect(instance).to.be.a(HouseHold.InlineResponse200HydraView);
    });

    it('should have the property id (base name: "@id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new HouseHold.InlineResponse200HydraView();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "@type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new HouseHold.InlineResponse200HydraView();
      //expect(instance).to.be();
    });

    it('should have the property hydrafirst (base name: "hydra:first")', function() {
      // uncomment below and update the code to test the property hydrafirst
      //var instane = new HouseHold.InlineResponse200HydraView();
      //expect(instance).to.be();
    });

    it('should have the property hydralast (base name: "hydra:last")', function() {
      // uncomment below and update the code to test the property hydralast
      //var instane = new HouseHold.InlineResponse200HydraView();
      //expect(instance).to.be();
    });

    it('should have the property hydranext (base name: "hydra:next")', function() {
      // uncomment below and update the code to test the property hydranext
      //var instane = new HouseHold.InlineResponse200HydraView();
      //expect(instance).to.be();
    });

  });

}));
