/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200HydraSearchHydraMapping model module.
 * @module model/InlineResponse200HydraSearchHydraMapping
 * @version 1.0.0
 */
class InlineResponse200HydraSearchHydraMapping {
    /**
     * Constructs a new <code>InlineResponse200HydraSearchHydraMapping</code>.
     * @alias module:model/InlineResponse200HydraSearchHydraMapping
     */
    constructor() { 
        
        InlineResponse200HydraSearchHydraMapping.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200HydraSearchHydraMapping</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200HydraSearchHydraMapping} obj Optional instance to populate.
     * @return {module:model/InlineResponse200HydraSearchHydraMapping} The populated <code>InlineResponse200HydraSearchHydraMapping</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200HydraSearchHydraMapping();

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], 'String');
            }
            if (data.hasOwnProperty('property')) {
                obj['property'] = ApiClient.convertToType(data['property'], 'String');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * @member {String} @type
 */
InlineResponse200HydraSearchHydraMapping.prototype['@type'] = undefined;

/**
 * @member {String} variable
 */
InlineResponse200HydraSearchHydraMapping.prototype['variable'] = undefined;

/**
 * @member {String} property
 */
InlineResponse200HydraSearchHydraMapping.prototype['property'] = undefined;

/**
 * @member {Boolean} required
 */
InlineResponse200HydraSearchHydraMapping.prototype['required'] = undefined;






export default InlineResponse200HydraSearchHydraMapping;

