/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse200HydraView model module.
 * @module model/InlineResponse200HydraView
 * @version 1.0.0
 */
class InlineResponse200HydraView {
    /**
     * Constructs a new <code>InlineResponse200HydraView</code>.
     * @alias module:model/InlineResponse200HydraView
     */
    constructor() { 
        
        InlineResponse200HydraView.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200HydraView</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200HydraView} obj Optional instance to populate.
     * @return {module:model/InlineResponse200HydraView} The populated <code>InlineResponse200HydraView</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200HydraView();

            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('hydra:first')) {
                obj['hydra:first'] = ApiClient.convertToType(data['hydra:first'], 'String');
            }
            if (data.hasOwnProperty('hydra:last')) {
                obj['hydra:last'] = ApiClient.convertToType(data['hydra:last'], 'String');
            }
            if (data.hasOwnProperty('hydra:next')) {
                obj['hydra:next'] = ApiClient.convertToType(data['hydra:next'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} @id
 */
InlineResponse200HydraView.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
InlineResponse200HydraView.prototype['@type'] = undefined;

/**
 * @member {String} hydra:first
 */
InlineResponse200HydraView.prototype['hydra:first'] = undefined;

/**
 * @member {String} hydra:last
 */
InlineResponse200HydraView.prototype['hydra:last'] = undefined;

/**
 * @member {String} hydra:next
 */
InlineResponse200HydraView.prototype['hydra:next'] = undefined;






export default InlineResponse200HydraView;

