/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse200HydraSearchHydraMapping from './InlineResponse200HydraSearchHydraMapping';

/**
 * The InlineResponse200HydraSearch model module.
 * @module model/InlineResponse200HydraSearch
 * @version 1.0.0
 */
class InlineResponse200HydraSearch {
    /**
     * Constructs a new <code>InlineResponse200HydraSearch</code>.
     * @alias module:model/InlineResponse200HydraSearch
     */
    constructor() { 
        
        InlineResponse200HydraSearch.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse200HydraSearch</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse200HydraSearch} obj Optional instance to populate.
     * @return {module:model/InlineResponse200HydraSearch} The populated <code>InlineResponse200HydraSearch</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200HydraSearch();

            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('hydra:template')) {
                obj['hydra:template'] = ApiClient.convertToType(data['hydra:template'], 'String');
            }
            if (data.hasOwnProperty('hydra:variableRepresentation')) {
                obj['hydra:variableRepresentation'] = ApiClient.convertToType(data['hydra:variableRepresentation'], 'String');
            }
            if (data.hasOwnProperty('hydra:mapping')) {
                obj['hydra:mapping'] = ApiClient.convertToType(data['hydra:mapping'], [InlineResponse200HydraSearchHydraMapping]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} @type
 */
InlineResponse200HydraSearch.prototype['@type'] = undefined;

/**
 * @member {String} hydra:template
 */
InlineResponse200HydraSearch.prototype['hydra:template'] = undefined;

/**
 * @member {String} hydra:variableRepresentation
 */
InlineResponse200HydraSearch.prototype['hydra:variableRepresentation'] = undefined;

/**
 * @member {Array.<module:model/InlineResponse200HydraSearchHydraMapping>} hydra:mapping
 */
InlineResponse200HydraSearch.prototype['hydra:mapping'] = undefined;






export default InlineResponse200HydraSearch;

