/**
 * HouseHold
 * HouseHold API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductCollectionjsonld model module.
 * @module model/ProductCollectionjsonld
 * @version 1.0.0
 */
class ProductCollectionjsonld {
    /**
     * Constructs a new <code>ProductCollectionjsonld</code>.
     * @alias module:model/ProductCollectionjsonld
     */
    constructor() { 
        
        ProductCollectionjsonld.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductCollectionjsonld</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductCollectionjsonld} obj Optional instance to populate.
     * @return {module:model/ProductCollectionjsonld} The populated <code>ProductCollectionjsonld</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductCollectionjsonld();

            if (data.hasOwnProperty('@context')) {
                obj['@context'] = ApiClient.convertToType(data['@context'], 'String');
            }
            if (data.hasOwnProperty('@id')) {
                obj['@id'] = ApiClient.convertToType(data['@id'], 'String');
            }
            if (data.hasOwnProperty('@type')) {
                obj['@type'] = ApiClient.convertToType(data['@type'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('product')) {
                obj['product'] = ApiClient.convertToType(data['product'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} @context
 */
ProductCollectionjsonld.prototype['@context'] = undefined;

/**
 * @member {String} @id
 */
ProductCollectionjsonld.prototype['@id'] = undefined;

/**
 * @member {String} @type
 */
ProductCollectionjsonld.prototype['@type'] = undefined;

/**
 * @member {String} name
 */
ProductCollectionjsonld.prototype['name'] = undefined;

/**
 * @member {String} category
 */
ProductCollectionjsonld.prototype['category'] = undefined;

/**
 * @member {String} product
 */
ProductCollectionjsonld.prototype['product'] = undefined;

/**
 * @member {String} id
 */
ProductCollectionjsonld.prototype['id'] = undefined;






export default ProductCollectionjsonld;

